/**
 * The directory where the latest repository content is located.
 */
export const CURRENT_PROJECT_DIR = ".";

/**
 * The directory where the repository content of the previous release is located.
 * See `.github/workflows/release.yml`.
 */
export const PREVIOUS_PROJECT_DIR = "previous-release";

/**
 * The name of the changeset file that records the change history of tokens.
 * This file is automatically generated on CI and immediately consumed by Changesets, so it is not persisted in the repository.
 */
export const TOKENS_CHANGESET_FILENAME =
  ".changeset/auto-generated-token-changes.md";

/** Theme group to directory name mapping */
export const GROUP_NAME_MAP: Partial<Readonly<Record<string, string>>> = {
  DKN: "daikin",
  AAF: "aaf",
};

/** Theme name to directory name mapping */
export const THEME_NAME_MAP: Partial<Readonly<Record<string, string>>> = {
  Light: "Light",
  Dark: "Dark",
};
