/**
 * The directory where the latest repository content is located.
 */
export const CURRENT_PROJECT_DIR = ".";

/**
 * The directory where the repository content of the previous release is located.
 * See `.github/workflows/release.yml`.
 */
export const PREVIOUS_PROJECT_DIR = "previous-release";

export const THEMES_DIR = "themes";

export const BUILD_DIR = "build";

/** Number of tokens to pick up in a changeset. */
export const PICK_TOKEN_COUNT = 5;

/**
 * The directory that stores changeset files.
 */
export const CHANGESET_DIR = ".changeset";

/**
 * The prefix of the changeset file that records the change history of tokens.
 * This file is automatically generated on CI and immediately consumed by Changesets, so it is not persisted in the repository.
 *
 * The filename must change whenever the content changes; otherwise, in pre-release mode, Changesets
 * treats a re-generated file with the same name as an already-consumed changeset and ignores it.
 * To keep the filename deterministic (and stable when content is unchanged), we append a content hash.
 */
export const TOKENS_CHANGESET_FILENAME_PREFIX = "auto-generated-token-changes";

/** Theme group to directory name mapping */
export const GROUP_NAME_MAP: Partial<Readonly<Record<string, string>>> = {
  DKN: "daikin",
  AAF: "aaf",
  Density: "density",
};

/** Theme name to directory name mapping */
export const THEME_NAME_MAP: Partial<Readonly<Record<string, string>>> = {
  Light: "Light",
  Dark: "Dark",
  Default: "Default",
  Compact: "Compact",
};
